version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == master]
    ports:
      - "9090:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    external: true
